stages:
- build
- deploy

variables:
  IMAGE_TAG_NAME: $CI_REGISTRY/yashhere/docker-hugo:$CI_COMMIT_REF_NAME
  
build:
  stage: build
  when: on_success
  only:
    - master
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $IMAGE_TAG_NAME .
    - docker push $IMAGE_TAG_NAME